import {
  supportDesk,
  SocialMediaApp,
  FeedbackApp,
  adminDashboard,
  catalog,
  ecommerceSanity,
  githubFinder,
  facturare,
  facebook,
  screen,
} from './assets/index'
export const data = [
  {
    img: `${SocialMediaApp}`,
    title: 'SocialMediaApp',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla veniam architecto nam incidunt corporis ea, culpa, repudiandae consequuntur nesciunt sed numquam ipsa minima dolorem fugiat! Commodi, voluptas! Dolore, accusamus velit totam provident unde consequuntur explicabo, itaque obcaecati perferendis modi maxime!',
    sub: 'lorem10201201201021',
    linkYt: 'https://www.youtube.com/watch?v=F6HTUQzfPFA&feature=youtu.be',
    linkGithub: 'https://github.com/EduardCirstea/Fullstack-SocialMediaApp',
  },
  {
    img: `${supportDesk}`,
    title: 'Support Desk',
    sub: 'lorem10201201201021',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla veniam architecto nam incidunt corporis ea, culpa, repudiandae consequuntur nesciunt sed numquam ipsa minima dolorem fugiat! Commodi, voluptas! Dolore, accusamus velit totam provident unde consequuntur explicabo, itaque obcaecati perferendis modi maxime!',
    linkYt: 'https://www.youtube.com/watch?v=nl7kFVGv6bY',
    linkGithub: 'https://github.com/EduardCirstea/support-ticket',
  },
  {
    img: `${FeedbackApp}`,
    title: 'Feedback App',
    sub: 'sub',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla veniam architecto nam incidunt corporis ea, culpa, repudiandae consequuntur nesciunt sed numquam ipsa minima dolorem fugiat! Commodi, voluptas! Dolore, accusamus velit totam provident unde consequuntur explicabo, itaque obcaecati perferendis modi maxime!',
    linkYt: 'https://youtu.be/H1hHWz1xs3A ',
    linkGithub: 'https://github.com/EduardCirstea/github-finder-app',
  },
  {
    img: `${adminDashboard}`,
    title: 'Admin Dashboard',
    sub: 'sub',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla veniam architecto nam incidunt corporis ea, culpa, repudiandae consequuntur nesciunt sed numquam ipsa minima dolorem fugiat! Commodi, voluptas! Dolore, accusamus velit totam provident unde consequuntur explicabo, itaque obcaecati perferendis modi maxime!',
    linkYt: 'https://www.youtube.com/watch?v=MDAsS329pFI',
    linkGithub: 'https://github.com/EduardCirstea/Admin-dashboard',
  },
  {
    img: `${catalog}`,
    title: 'Catalog Online',
    sub: 'sub',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla veniam architecto nam incidunt corporis ea, culpa, repudiandae consequuntur nesciunt sed numquam ipsa minima dolorem fugiat! Commodi, voluptas! Dolore, accusamus velit totam provident unde consequuntur explicabo, itaque obcaecati perferendis modi maxime!',
    linkYt: '#',
    linkGithub: 'https://github.com/EduardCirstea/Catalog-studentesc',
  },
  {
    img: `${ecommerceSanity}`,
    title: 'E-commerce',
    sub: 'sub',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla veniam architecto nam incidunt corporis ea, culpa, repudiandae consequuntur nesciunt sed numquam ipsa minima dolorem fugiat! Commodi, voluptas! Dolore, accusamus velit totam provident unde consequuntur explicabo, itaque obcaecati perferendis modi maxime!',
    linkYt: 'https://www.youtube.com/watch?v=WHAbMjBfA-c',
    linkGithub: 'https://github.com/EduardCirstea/Ecommerce_nextjs',
  },
  {
    img: `${githubFinder}`,
    title: 'Github Finder',
    sub: 'sub',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla veniam architecto nam incidunt corporis ea, culpa, repudiandae consequuntur nesciunt sed numquam ipsa minima dolorem fugiat! Commodi, voluptas! Dolore, accusamus velit totam provident unde consequuntur explicabo, itaque obcaecati perferendis modi maxime!',
    linkYt: 'https://www.youtube.com/watch?v=IEJJBuDIONQ',
    linkGithub: 'https://github.com/EduardCirstea/github-finder-app',
  },
  {
    img: `${facturare}`,
    title: 'Facturare',
    sub: 'sub',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla veniam architecto nam incidunt corporis ea, culpa, repudiandae consequuntur nesciunt sed numquam ipsa minima dolorem fugiat! Commodi, voluptas! Dolore, accusamus velit totam provident unde consequuntur explicabo, itaque obcaecati perferendis modi maxime!',
    linkYt: 'https://www.youtube.com/watch?v=EtM1kLm7MTM',
    linkGithub: 'https://github.com/EduardCirstea/App-facturare/',
  },
  {
    img: `${facebook}`,
    title: 'Facebook',
    sub: 'sub',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla veniam architecto nam incidunt corporis ea, culpa, repudiandae consequuntur nesciunt sed numquam ipsa minima dolorem fugiat! Commodi, voluptas! Dolore, accusamus velit totam provident unde consequuntur explicabo, itaque obcaecati perferendis modi maxime!',
    linkYt: '#',
    linkGithub: 'https://github.com/EduardCirstea/Facebook-clone',
  },
  {
    img: `${screen}`,
    title: 'Portfolio',
    sub: 'sub',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla veniam architecto nam incidunt corporis ea, culpa, repudiandae consequuntur nesciunt sed numquam ipsa minima dolorem fugiat! Commodi, voluptas! Dolore, accusamus velit totam provident unde consequuntur explicabo, itaque obcaecati perferendis modi maxime!',
    linkYt: '#',
    linkGithub: '#',
  },
]
